Makefile
demo/getting_started/interfaces_test.go
ygen/commongen.go

This change adds support for a smoke test for ygot that ensures the end-to-end generation pipeline is creating parsable code.
```
* (M) Makefile
- Make sure that go generate is called for make all, add make
clean.
* (M) demo/getting_started/interfaces_test.go
- Add a smoke test for OpenConfig model generation using the Go
parser.
```

Add additional test cases

---

ytypes/list.go

```
* (M) ytypes/list.go
- When the key used within a map was not equal to the YANG list's
field that specified the key, the error message was slightly
cryptic. Fix this based on user bug.
```

Make error message for mismatched list keys clearer.

---

demo/getting_started/pkg/ocdemo/ocdemo.go
exampleoc/README.md

This PR fixes a couple of minor issues that cause problems with external build systems.
```
* (M) demo/getting_started/pkg/ocdemo/ocdemo.go
- Add package comment for ocdemo.
* (M) exampleoc/oc.go
- Make package name match directory name to ensure build
system compliance.
```

Resolve golint/govet issues.

---

ytypes/common.go

This resolves the issue introduced by adding leading slash to paths in root elements.

Remove leading slash from absolute paths in schema handler.

---

generator/generator.go
ygen/codegen_test.go
ygen/goelements_test.go
ygen/gogen.go
ygen/gogen_test.go
ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-compress.formatted-txt
ygen/testdata/schema/openconfig-options-explicit.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress.formatted-txt

```
* (M) exampleoc/oc.go
- Update generated code, fixes go vet issues.
* (M) generator/generator.go
* (M) ygen/codegen_test.go
- Change to fmt.Fprintln or fmt.Fprint rather than Fprintf which was
causing %(MISSING)v output.
* (M) ygen/gogen.go
- Fix template that inserted %%.
* (M) ygen/gogen_test.go
* (M) ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
* (M) ygen/testdata/schema/openconfig-options-compress.formatted-txt
* (M) ygen/testdata/schema/openconfig-options-explicit.formatted-txt
* (M) ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
* (M) ygen/testdata/schema/openconfig-options-nocompress.formatted-txt
- Fix tests that expected %%.
```

Fix govet issues in the generated code.

---

experimental/ygotutils/getnode.go
experimental/ygotutils/getnode_test.go
ytypes/schema_tests/validate_test.go

- Fix handling for ptr types in NewNode (would previously return correct type, but not initialized).
- Add coverage to handle non-ptr types.
- Add tests with exampleoc schema.
- Remove schema return value in public GetNode API, as this can be obtained from SchemaTree.

Fix NewNode ptr type handling, add real schema tests.

---

ytypes/common.go
ytypes/leaf_list_test.go
ytypes/list.go
ytypes/list_test.go

Using SchemaTree sometimes leads to surprising results for users due to how the OC schema is laid out. Specifically, schemas that might be expected to be structs are lists since a list schema is also a container for the list element e.g. 
oc.SchemaTree["Device_Components_Component"] is actually a list, not a list element.
But it seems reasonable that the user may want to unmarshal into what they believe to be a struct in the schema.
This change addresses that case by checking the format of the incoming schema: if it's a struct ptr, we attempt the unmarshal is into a list element as well as a list. This is safe because the struct type must still be correct wrt the JSON being unmarshaled.

Add ability to unmarshal into individual list element structs.

---

ytypes/leaf.go
ytypes/leaf_test.go
ytypes/schema_tests/validate_test.go
ytypes/util_reflect.go
ytypes/util_types.go

Enum types in unions were not handled. Usually enums are checked by compiler but in the case of union, there may be other types possible, hence enum must be added to the set of possible types to check against (although the actual value need not be checked because the compiler will do this).

Add missing validation handling for enum types in union.

---

demo/device/devicedemo.go
demo/device/devicedemo_test.go
demo/device/testdata/device-ietf.json
demo/device/testdata/device.json
ygot/render.go
ygot/render_test.go

When a union was serialised to JSON then if an enumerated value existed within that union it was printed as a string rather than as the string value. This CL corrects this serialisation.

Fix bug with serialisation of enumeration values in unions.

---

ygen/gogen.go
ygen/gogen_test.go
ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-compress.formatted-txt
ygen/testdata/schema/openconfig-options-explicit.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress.formatted-txt
ygot/struct_validation_map_test.go
ygot/types.go

This CL adds the ability to call ΛEnumTypeMap() on a generated struct to retrieve the set of types that are associated with enums within the generated code file.

Add function to access ΛEnumTypes from generated code.

---

util/reflect.go
ygen/gogen.go
ygen/yang_helpers.go
ytypes/common_test.go
ytypes/container.go
ytypes/leaf.go
ytypes/leaf_test.go
ytypes/list.go
ytypes/util_schema.go
ytypes/util_types.go

Unions with enums depend on new type resolution in the generated code. 
Enum types are strings in JSON source tree. To determine whether they can be represented as enums, the list of all possible enum types and their values is needed from the local schema context. 
If any of these values match, the field is cast as the corresponding type that implements the union interface. Otherwise, unmarshal is attempted into the other, non-enum types.

Add handling for unmarshalling unions with enums.

---

demo/bgp/main_test.go
ygot/render.go
ygot/render_test.go
ygot/struct_validation_map.go

See this diff:
```diff
{
-  "Cisco-IOS-XR-crypto-sam-cfg:Cisco-IOS-XR-crypto-ssh-cfg:crypto": {
-    "ssh": {
+  "Cisco-IOS-XR-crypto-sam-cfg:crypto": {
+    "Cisco-IOS-XR-crypto-ssh-cfg:ssh": {
```
In the case of the 'crypto' leaf, since it is a different module to its SSH child, it was erroneously rendered. This is based on an assumption in the `ygot` library around where `ygen` path compresses, which was not robust in the case of the fake root and uncompressed schemas. This CL adds a fix, and tests for this case.

Fix issue with marshalling entities at the root which are in different modules to their children.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

This CL adds two sets of functionality:
* Exposes the MergeStruct functionality to copy a struct to a new struct as a public `DeepCopy` API. This is implemented for any `GoStruct`.
* Adds the ability to merge entries from two maps, as long as their keys are not identical.

Add DeepCopy, merging of structs with maps.

---

util/debug.go
ytypes/list.go

Unmarshal as container introduced a bug where a deep copy of the schema node was not done before modifying.

Fix unmarshal list as container.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

Fix bug found by @ejbrever in `MergeStructs`
```
* (M) ygot/struct_validation_map.go
- Fix an issue whereby an empty dst struct ptr was always used
(created with reflect.New) in the case that structs were being
merged. This means that if BuildEmptyTree had been used on the
structs being merged, then even empty branches would be
overwritten.
- Return an error if a non-struct ptr is non-nil in two different
structs.
* (M) ygot/struct_validation_map_test.go
- Add testing for returned errors.
- Add testing to validate the BuildEmptyTree issue above.
```

Fix bug whereby BuildEmptyTree + Merge results in empty struct.

---

proto/yext/yext.proto

This CL updates the field numbers in `yext.proto` to use the reservations that have been provided from the protobuf team.

Update field numbers based on the global protobuf reservation.

---

demo/getting_started/interfaces.go
util/errs.go
util/errs_test.go
util/reflect.go
ytypes/any_type_test.go
ytypes/binary_type_test.go
ytypes/bitset_type_test.go
ytypes/bool_type_test.go
ytypes/choice_test.go
ytypes/common_test.go
ytypes/container.go
ytypes/container_test.go
ytypes/decimal_type_test.go
ytypes/empty_type_test.go
ytypes/int_type.go
ytypes/int_type_test.go
ytypes/leaf.go
ytypes/leaf_list.go
ytypes/leaf_list_test.go
ytypes/leaf_test.go
ytypes/list.go
ytypes/list_test.go
ytypes/schema_tests/validate_test.go
ytypes/string_type_test.go
ytypes/unmarshal_test.go
ytypes/util_schema.go
ytypes/validate.go
ytypes/validate_test.go

- use NewErrs instead of AppendErr(errors, ...
- change signatures to return Errors so that caller can immediately print return value
- make various error strings consistent:
- wanted error -> want error
- use "want error?" only for bools
- use errs where util.Errors are returned 
- other minor cleanups

Fix various nits

---

ygot/pathstrings.go
ygot/pathstrings_test.go

The "/" is only needed in formatted string from PathToString.
Also add a short sanity unit test for PathToStrings, more detailed cases
are already covered via TestPathToString.

Remove leading "/" from PathToStrings

---

util/reflect.go

Validation should not fail due to schema error, rather log error message.

Continue validation on schema error.

---

ygot/pathstrings.go
ygot/pathstrings_test.go

In order to produce paths identical to Path.Elem, take the unescaped
paths and strigify them, instead of using raw strings originally
provided.
Note: this broke more tests than I was expecting. Please take a look at those to make sure I'm not actually breaking things.

Handle escape characters on string->Path.Element conversion

---

demo/device/devicedemo.go
demo/device/testdata/device-ietf.json
demo/device/testdata/device.json
ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

```
* (M) ygot/struct_validation_map.go:
* (M) ygot/struct_validation_map_test.go:
- Add an opts slice to MergeStructs which allows options to be
specified when merging structs. Particularly, allow overwrite of a
pointer field that is specified in both structs. In the case that
the IfEqual bool is set true, merging is only allowed when the two
values are equal. This is particularly aimed to handle merging
lists which always have equal keys.
- Change default behaviour for merging map structs to be allowing
leaf overwrites.
```

Add option framework for MergeStructs.

---

ytypes/validate.go

```
* (M) ytypes/validate.go
- LeafrefOptions was previously implementing ValidationOpts as
a non-pointer receiver. The handling code expected the
implementation to be a pointer - this CL changes the receiver to
be a pointer receiver.
```

Fix ValidationOpts interface implementation for LeafrefOptions.

---

ygot/diff.go
ygot/diff_test.go
ygot/render.go
ygot/render_test.go

This CL adds the public API for diffing two `GoStructs`. It returns a `gnmi.Notification` message with the difference between two structs.
Schema-based tests rather than mock inputs will be added in a subsequent CL.

Add ygot.Diff public API to diff two GoStructs

---

ygot/diff_test.go

```
* (M) ygot/diff_test.go
- Some protoc implementations add additional fields to messages
such that use of TypedValue without a field name causes a
compliation error. It is safe to use unkeyed fields in a
oneof generated field, so this is left unchanged.
```

Minor fix for use of unkeyed field in struct literal in proto.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go
ygot/testdata/invalid-struct.json-txt

```
* (M) ygot/struct_validation_map.go
* (M) ygot/struct_validation_map_test.go
- Add an option to skip validating a struct in EmitJSON. The
default is to validate, but this allows a user who explicitly
wants to skip all validation to force JSON marshalling.
```

Add option to EmitJSONConfig to skip validation.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

```
* (M) ygot/struct_validation_map.go
* (M) ygot/struct_validation_map_test.go
- When a struct is initialised with BuildEmptyTree, many of its
branches may not be populated - but then have a nil value, such
that comparisons with a struct literal are not equal. This
results in complexities in testing and equality within consuming
code. This commit implements a pruning function that removes any
struct pointer field of a GoStruct which is found to be empty
recursively.
```

Implement a function to remove empty branches from a GoStruct.

---

.travis.yml
util/debug.go
ytypes/schema_tests/race_test.go

This CL changes the `util.Intent()` and `util.Dedent()` functions to only manipulate global state when `debugLibrary` is enabled, fixing a race condition that would occur in non-debugging cases.

Gate global variable manipulation on debugLibrary.

---

generator/generator.go
ygen/codegen.go
ygen/codegen_test.go
ygen/gogen.go
ygen/gogen_test.go
ygen/testdata/structs/openconfig-list-enum-key.getters-append.formatted-txt

This commit adds:
- A flag (`GenerateDeleteMethod`) to `ygen` that creates DeleteXXX(<list key spec>) methods for lists within the output code.
- Unit tests for the above in `ygen`.

Add support for Delete generation.

---

ygot/diff.go
ygot/diff_test.go
ygot/render.go

```
* (M) ygot/{diff,diff_test,render}.go
- Add an options input to the diff function such that its behaviour
can be modified.
- Add an option that allows a user to specify that struct fields
that map to >1 path should only be output at their least specific
path.
```

Add implementation of de-duplication of paths in diffs.

---

ygot/pathstrings.go
ygot/pathstrings_test.go

```
* (M) ygot/pathstrings*
- Add support for PathToSchemaPath which extracts only element
names, ignoring keys from the supplied path.
```

Add support for extracting the schemapath from a gNMI Path message.

---

.travis.yml
demo/protobuf_getting_started/demo.go

When protobufs include unknown field tags, then struct literals must use field names, rather than anonymous initialisers - this PR fixes the tests.

Fix broken test in HEAD@master.

---

generator/generator.go

This PR fixes an issue whereby there are missing `log.Exitf` arguments in the input code.

Fix missing log.Exitf arguments.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

```
* (M) ygot/struct_validation_map*
- Add a public EnumName API which resolves a GoEnum to its string
value within the YANG schema. Always ignores the module name.
```

Add EnumName public API.

---

ytypes/leafref.go
ytypes/validate.go

```
* (M) ytypes/leafref.go
- Skip log.Errorf if leafref validation fails when IgnoreMissingData
is set.
* (M) ytypes/validate.go
- Add Log bool to LeafrefOptions to allow control of logging
behaviour.
```
This PR addresses some overly chatty logging observed when `IgnoreMissingData` is set in a `Validate` `LeafrefOption`.

Add option not to log when leafref validation is skipped.

---

ygot/pathstrings.go
ygot/pathstrings_test.go

Fixes a silly NPE in the public API :-(
```
* (M) ygot/pathstrings.go
* (M) ygot/pathstrings_test.go
- Add implementation and tests for a nil path being passed to
PathToX methods.
```

Add error handling for nil paths.

---

ygen/gogen.go
ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-compress.formatted-txt
ygen/testdata/schema/openconfig-options-explicit.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress.formatted-txt
ytypes/container.go
ytypes/container_test.go
ytypes/list.go
ytypes/list_test.go
ytypes/schema_tests/testdata/basic-extra.json
ytypes/schema_tests/testdata/bgp-example.json
ytypes/schema_tests/validate_test.go
ytypes/unmarshal.go
ytypes/unmarshal_test.go

Where devices have augmentation to the YANG schema, additional fields may be present in the JSON supplied to `Unmarshal`. Prior to this PR, this would result in errors being thrown relating to those missing fields. This change adds a new `UnmarshalOpt` interface which can be optionally supplied to `Unmarshal` in the generated code. When supplied it ensures that an error is not thrown for such additional fields.

Add an option to ignore additional fields in input JSON.

---

demo/gnmi_telemetry/gnmi.go
experimental/ygotutils/common.go
util/reflect.go

It looks like HEAD@master for Go has added error handling for incorrect `Errorf` formatting strings, and detection of them in `Errorln`.
This fixes the tests.

Fix ygot with latest Go master build.

---

ytypes/util_test.go
ytypes/util_types.go

gNMI PathElem carries keys in Key field. For struct key types, the Key field carries more than one <key, value> pairs. Source type is just string, but destination field in struct can be string, enum etc. This helper will be used to convert given string to given type while unmarshalling a gNMI notification into GoStruct.

Add StringToType helper to use with gNMI notification unmarshalling

---

ytypes/common_test.go
ytypes/list.go
ytypes/list_test.go
ytypes/util_schema.go
ytypes/util_test.go
ytypes/util_types.go

makeKeyForInsert function ,which already exists in list.go, have capability to create a map key given a map value. This change adds another helper to create a map value given a map[string]string assuming from the gNMI PathElem. After this change, it will be possible to create a map entry given a gNMI Path with Key field populated.

Add ygot helper to create map element value

---

util/common.go
util/common_test.go
util/reflect.go
ygot/render.go
ygot/render_test.go
ytypes/list.go
ytypes/node.go
ytypes/node_test.go

- Added an internal function to use  while unmarshalling a gNMI notification into GoStruct
- Behavior of the internal function can be modified with the flags provided
- Exposed GetOrCreateNode function to use while retrieving a node corresponding to given gNMI path
This change will be followed by a set of changes that use the internal function mentioned above with different combination of flags. We aim to consolidate existing similar functions listed below;
See **NewNode** and **GetNode** in _experimental/ygotutils/getnode.go_
See **GetNodes** in _util/reflect.go_

Add utility to validate given gNMI Path against given schema 

---

util/reflect.go
util/reflect_test.go
ytypes/list.go
ytypes/list_test.go

- Added utility to compare types of given reflect.Values
- Fixed the panic that occurs while setting unmatching types in makeKeyForInsert
- Add tests for TestInsertAndGetKey

Fix the panic occurs when key and value fields don't match in makeKeyForInsert

---

.travis.yml
ygot/pathtranslate/pathtranslate.go
ygot/pathtranslate/pathtranslate_test.go

With gNMI Path 0.4, PathElem is used to describe a path. It discriminates name and key fields. With the utility added in this change, it will be possible to translate given string slice into PathElem slice in a schema aware way.

Add utility to translate given string slice as gNMI PathElem in a schema aware way

---

ygot/render.go
ygot/render_test.go
ygot/schema_tests/schema_test.go
ygot/schema_tests/testdata/unsetenum.json
ytypes/node_test.go

```
* (M) ygot/render*
- Resolve an issue whereby a union that had the UNSET value of
an enumeration specified explicitly within it would be rendered
as an empty string in output JSON. This issue was due to not
checking whether the enumeration was set to a non-zero value
when handling such cases.
- Added unit tests covering this bug.
* (M) ygot/schema_tests/*
- Added an integration test against the schema to validate the
above issue.
```

Resolve bug with unset enum in union.

---

ygot/render.go
ytypes/node.go
ytypes/node_test.go
ytypes/schema_tests/get_test.go
ytypes/schema_tests/validate_test.go

```
* (M) ygot/render.go
- Make PathKeyFromStruct a public function. This returns the
map[string]string required in a gNMI Notification to an
external caller.
* (M) ytypes/node.go
- Update retrieveNode (and hence Get/GetOrCreateNode) to store
the path to a retrieved node when it returns the value. This
increases the utility of the function when in use within a
gNMI implementation.
* (M) ytypes/.../*test.go
- Add test coverage for the retrieveNode function against
crafted and generated schemas.
```

Update retrieveNode to return paths.

---

util/common.go
util/common_test.go
ygot/render.go
ygot/render_test.go
ytypes/node.go
ytypes/schema_tests/get_test.go

```
* (M) util/*
- Add helper functions for gNMI paths that allow implementation
of prefix finding for a set of paths, and trimming a prefix
from a path.
* (M) ygot/render*.go
- Add a render function which can take a struct value and return
it as a gNMI typedvalue.
```

Add helper functions for gNMI implementation.

---

scripts/coverage.sh

```
* (M) scripts/coverage.sh
- Avoid testing coverage for test packages that are themselves
tests.
```
This is just some internal housekeeping, since we track the coverage and report on it in PRs where it decreases significantly (as a blocking check), then we want to avoid checking files where we don't expect coverage.

Update scripts/coverage.sh to exclude tests.

---

testutil/testutil.go
testutil/testutil_test.go
ygot/render.go
ygot/render_test.go

```
* (M) testutil/testutil.go
* (M) testutil/testutil_test.go
-  Add support for checking equality of GetResponse.
* (M) ygot/render.go
* (M) ygot/render_test.go
- Cleanly handle a nil struct in marshalStruct.
```
Porting change into GitHub.

GetResponse check in testutil, nil struct check.

---

ygen/codegen.go
ygen/gogen.go
ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-compress.formatted-txt
ygen/testdata/schema/openconfig-options-explicit.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress.formatted-txt
ygen/yang_helpers.go
ygen/yang_helpers_test.go
ygot/render.go
ygot/render_test.go
ytypes/types.go

This PR adds a new function into generated code that produces a representation of the schema that is being used. It gives a reusable mechanism to get the root, schema tree, and the unmarshal function for a calling application.

Add a generated Schema function to return schema details.

---

ygot/render_test.go
ytypes/leafref.go

This resolves a performance issue with large datasets where `IgnoreMissingData` still resulted in validations being run, and hence significant performance impact.

Return from leafref validation quickly if IgnoreMissingData is set.

---

testutil/testutil.go
testutil/testutil_test.go
ygot/render.go
ygot/render_test.go
ytypes/node.go

This PR updates the behaviour of the return arguments for some retrieval
functions to allow Subscribe implementation, adds further test util
helpers and fixes a panic in findUpdatedLeaves.
```
* (M) testutil/testutil(_test)?.go
- Add support for checking the equality of two slices of
SubscribeResponse messages, and individual SubscribeResponse
messages.
* (M) ygot/render(_test)?.go
- Fix a panic which occurred when a nil GoStruct was provided to
TogNMINotifications.
* (M) ytypes/node.go
- Ensure that we comply with the gNMI specification as to when to
return NotFound vs. InvalidArgument.
```

testutil enhancements; render panic fixes; error updates.

---

ygot/diff.go
ygot/diff_test.go
ygot/render.go
ygot/render_test.go
ygot/schema_tests/schema_test.go

```
* (M) ygot/{diff,diff_test,render,render_test}.go
- De-duplicate typed value creation code, and ensure that it
uniformly implements the rendering of a slices to TypedValue.
* (A) ygot/schema_tests/schema_test.go
- Add tests that cover discovered bug.
```

Fix rendering feature gap used with diff.

---

ygot/render.go
ygot/render_test.go

This CL ensures that EncodeTypedValue is robust to being handed
nil pointer values.

Handle nil-pointer fields in EncodeTypedValue.

---

testcmp/cmp.go

Fixes a linter issue whereby we were missing a package comment for testcmp.

Fix missing package comment for testcmp.

---

util/errs.go
util/errs_test.go
ytypes/container.go
ytypes/container_test.go
ytypes/schema_tests/validate_test.go
ytypes/validate_test.go

```
* (M) util/errs*
- Add functions to deduplicate util.Errors and prefix all errors in a
supplied util.Errors.
* (M) ytypes/{validate,container}*
- Ensure that when an error is returned by Validate() each path
element is not a separate error in the slice -- there was some
re-use of the errors slice that caused this to be the case. This
matters only to consumers that parse ytypes' return value as a
util.Errors, string users were unaffected.
- Ensure that where duplicate errors occur (same regexp, same schema
path) only one error is returned. In the future, we should track the
datatree path, but this is currently not possible without more major
refactoring of Validate().
* (M) ytypes/schema_tests/validate_test.go
- Add test cases checking error output.
```

Fix error formatting in Validate.

---

testcmp/cmp_test.go
testutil/testutil.go
testutil/testutil_test.go

```
* (M) testutil/testutil.go
- Avoid issues with a ptr being used for IgnoreTimestamp. This
is not needed since the struct is empty, and the argument is
always immutable. Generally, we should prefer non-ptr argument
types.
```

Update IgnoreTimestamp to be a non-ptr argument.

---

proto_generator/protogenerator.go

```
* (M) proto_generator/protogenerator.go
- Fix bug whereby we did not honour the enum package name supplied
to us -- fixes #271.
```

Honour enum package name.

---

ytypes/leafref.go
ytypes/leafref_test.go
ytypes/schema_tests/leafref_benchmark_test.go

Leafref validation currently takes too long. Turns out just by
memoizing datanode searches, performance can be greatly improved.
A benchmark with the following timings is also added, testing
different interface/subinterface configurations.
BenchmarkInterfaceLeafrefs1-12                 1        3291651711 ns/op
BenchmarkInterfaceLeafrefs2-12                 1        2371589139 ns/op
BenchmarkInterfaceLeafrefs3-12                 1        2410086282 ns/op
comparing with master branch:
BenchmarkInterfaceLeafrefs1-12                 1        199058379412 ns/op
BenchmarkInterfaceLeafrefs2-12                 1        9990951263 ns/op
BenchmarkInterfaceLeafrefs3-12                 1        2937779011 ns/op

Add memoization for datanode search during leafref validation

---

ygen/gogen.go
ytypes/leafref.go
ytypes/leafref_test.go

```
* (M) ygen/gogen.go
- Add a sanity check that a module is a valid OC module when
generating rather than panic.
* (M) ytypes/leafref.go
* (M) ytypes/leafref_test.go
- Ensure that we correctly detect where ".." should be consumed
in relative paths in the case that we have leafrefs in the
uncompressed schema.
```

Fix bug with relative leafrefs in uncompressed schemas.

---

ytypes/choice.go
ytypes/choice_test.go
ytypes/container.go
ytypes/container_test.go

Fixes #189 
Assumes default type value for scalars should be considered "unset", e.g.:
* enum => uint64(0)
* empty => false

Fix for panic when validating choice/container with enum/empty leaf

---

ygot/render.go

```
* (M) ygot/render.go
- Before this change, we calculate the paths that a field should be
mapped to before we check whether it is nil or not, we can avoid
doing any check of a struct field's path at all if we check whether
it was nil *before*.
```
Before this change (with lsdbparse updates made):
```
▶ go test -test.bench BenchmarkRenderLSP -cpuprofile cpu.out
goos: darwin
goarch: amd64
pkg: github.com/openconfig/lsdbparse
BenchmarkRenderLSP/simple_example/usePathElem=false-12         	   30000	     49375 ns/op
BenchmarkRenderLSP/larger_example/usePathElem=false-12         	    5000	    329816 ns/op
BenchmarkRenderLSP/simple_-_pathelem_path/usePathElem=false-12 	   50000	     39262 ns/op
BenchmarkRenderLSP/simple_example/usePathElem=true-12          	   20000	     66246 ns/op …
```

Optimise nil checking in rendering structs to Notifications.

---

ygen/genstate.go
ygen/goelements.go
ygen/goelements_test.go
ygen/gogen.go
ygen/gogen_test.go
ygen/protoelements.go
ygen/protoelements_test.go
ygen/protogen.go
ygen/protogen_test.go

While MappedType is exported, these unexported fields make this type less usable in other packages. For example, a user package can't easily check the `isEnumeratedValue` field to check whether it's an enum. While it is true that an accessor function can be used instead, you then can't set this field in tests.
My original thought behind only exporting NativeType was that these are "internal states", but since these are just accompanying properties of the type that describe it further, this argument doesn't make much sense, so this is just correcting a problem.
p.s. This change would resolve another issue you raised.

Export remaining MappedType fields

---

experimental/ygotutils/getnode_test.go
testcmp/cmp_test.go
util/reflect_test.go
ytypes/leaf_list_test.go
ytypes/node_test.go
ytypes/schema_tests/validate_test.go

Syncing changes. Description below:
The Message.String method is intended for debugging and does not guarantee
output stability. Code that relies on the output being stable for all time is
brittle and has unintentionally become a change detector for the proto package.

Fix targets to avoid unstable string comparisons

---

experimental/ygotutils/getnode_test.go
util/gnmi_test.go
ygot/diff.go
ygot/diff_test.go
ygot/pathtranslate/pathtranslate_test.go
ygot/render_test.go
ygot/struct_validation_map_test.go
ytypes/schema_tests/get_test.go
ytypes/schema_tests/validate_test.go

Generated protobuf messages contain internal data structures
that general purpose comparison functions (e.g., reflect.DeepEqual,
pretty.Compare, etc) do not properly compare. It is already the case
today that these functions may report a difference when two messages
are actually semantically equivalent.
Fix all usages by either calling proto.Equal directly if
the top-level types are themselves proto.Message, or by calling
cmp.Equal with the cmp.Comparer(proto.Equal) option specified.
This option teaches cmp to use proto.Equal anytime it encounters
proto.Message types.

Fix generic comparisons on protobuf messages

---

ygen/protogen.go
ygen/protogen_test.go
ygen/testdata/proto/proto-enums-addid.formatted-txt
ygen/testdata/proto/proto-enums.formatted-txt
ygen/testdata/proto/proto-enums.yang

YANG enum value names can have slashes in them. Currently, the proto generator will include any slashes in the proto enum. 
E.g. this YANG enum value:
enum "Foo/Bar";
Becomes this proto enum value, which has in invalid slash in the name:
ENUMNAME_Foo/Bar = 491 [(yext.yang_name) = "Foo/Bar"];

protogenerator: improve handling of disallowed characters in proto enums

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go
ypathgen/testdata/structs/choice-case-example.path-txt
ypathgen/testdata/structs/enum-module.path-txt
ypathgen/testdata/structs/openconfig-augmented.path-txt
ypathgen/testdata/structs/openconfig-camelcase.path-txt
ypathgen/testdata/structs/openconfig-enumcamelcase.path-txt
ypathgen/testdata/structs/openconfig-simple.path-txt
ypathgen/testdata/structs/openconfig-unione.path-txt
ypathgen/testdata/structs/openconfig-withlist.path-txt

The duplicate path structs are called "wildcard nodes". They are to resolve to paths that contain wildcards, while the non-wildcard versions of the path structs are to resolve to paths that do not contain any wildcard.
Wildcard here means a key value wildcard -- i.e. only when a keyed list is part of the path, may the path contain a wildcard.
Since a wildcard node is created for all but the fakeroot (which has an empty path), there are wildcard nodes whose paths cannot ever contain a wildcard (since they may not contain any lists). This is an optimization that may be done later.

Add duplicate path struct for each node (except the fake root)

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go
ypathgen/testdata/structs/choice-case-example.path-txt
ypathgen/testdata/structs/enum-module.path-txt
ypathgen/testdata/structs/openconfig-augmented.path-txt
ypathgen/testdata/structs/openconfig-camelcase.path-txt
ypathgen/testdata/structs/openconfig-enumcamelcase.path-txt
ypathgen/testdata/structs/openconfig-simple.path-txt
ypathgen/testdata/structs/openconfig-unione.path-txt
ypathgen/testdata/structs/openconfig-withlist.path-txt

- Refactor helper functions used to create list parameters and their key values.
- New functions generateChildConstructorsForList and generateChildConstructorsForLeafOrContainer.
- Make generateChildConstructors call the above new functions during its
execution depending on whether it's processing a list or container.

Autogenerate child constructor methods for wildcard nodes.

---

ypathgen/path_tests/path_test.go

exampleoc/oc.go and exampleocpath/ocpath.go are updated via their update.go scripts.
- oc.go is updated to the latest OpenConfig YANG models in the public repository.
- ocpath.go, in addition to updating to the latest YANG models, is updated with the wildcard child constructor methods that were implemented in #335

Add path tests for wildcard nodes

---

ygen/genstate.go
ygen/gogen.go

This is a refactoring effort. genState's numerous global state makes the code somewhat harder to understand -- this helps by removing the one that doesn't need to be a global variable.

Remove global var generatedUnionInterfaces and use a local var instead

---

ygen/codegen.go
ygen/genstate.go
ygen/genstate_test.go
ygen/goelements.go
ygen/goelements_test.go
ygen/gogen.go
ygen/gogen_test.go
ygen/protoelements.go
ygen/protoelements_test.go
ygen/protogen.go
ygen/protogen_test.go
ygen/schematree.go

Currently, genState contains all the internal state variables and
generation functions for both Go and proto, making the code more
confusing than necessary and changes to the code seemingly more
precarious due to the lack of clear separation between Go and proto
generation. This is a problem for both the reader of the code as well as
maintainers.
To help with this, genState is split into protoGenState, goGenState,
enumGenState, and genHelper. genHelper contains helpers used for
generation, and enumGenState contains functionality and internal state
used for generating enum names. These two are language independent.
protoGenState and goGenState then contains the language-specific
generation functionalities.
The generation methods are partitioned either into one of these new
smaller …

Split genState into smaller generators.

---

ytypes/leaf.go
ytypes/leaf_list.go
ytypes/node.go
ytypes/node_test.go
ytypes/unmarshal.go

TolerateJSONInconsistencies signals SetNode to tolerate inconsistencies
for val as if it were converted from JSON. As of right now, this is
specifically to deal with uint values being streamed as positive int
values.
The unexported encoding gNMIEncodingWithJSONTolerance is added to allow this exception handling
to occur within ytype's unmarshal codebase.

Add TolerateJSONInconsistencies option for SetNode

---

experimental/ygotutils/getnode_test.go
testutil/testutil.go
util/path_test.go
util/reflect.go
util/reflect_test.go
util/yang_test.go
ygen/codegen_test.go
ygen/goelements_test.go
ygen/gogen_test.go
ygen/protogen_test.go
ygen/schema_tests/schema_test.go
ygen/schemaparse_test.go
ygen/schematree_test.go
ygot/diff.go
ygot/diff_test.go
ygot/helpers_test.go
ygot/pathstrings_test.go
ygot/pathtranslate/pathtranslate_test.go
ygot/render_test.go
ygot/struct_validation_map.go
ygot/struct_validation_map_test.go
ytypes/common_test.go
ytypes/leaf_list_test.go
ytypes/leaf_test.go
ytypes/leafref.go
ytypes/leafref_test.go
ytypes/list_test.go
ytypes/node_test.go
ytypes/schema_tests/validate_test.go
ytypes/util_json.go

https://godoc.org/github.com/google/go-cmp/cmp:
> This package is intended to be a more powerful and safer alternative to reflect.DeepEqual for comparing whether two values are semantically equal.
yang.Entry still needs reflect.Equal because cmp.Equal doesn't seem to support the circular references it has despite cmp claiming to support graph comparison (stack overflow).
Note that some changes just trivially change (-got, +want) to (-want, +got) in the error message. I wanted to make everything consistent, but I stopped because I noticed a lack of consistency with `testutil.GenerateUnifiedDiff` always doing (-got, +want), and this style issue is not a big deal anyways.

Replace reflect.DeepEqual with cmp.Equal/Diff where possible

---

ygen/helpers.go
ygen/helpers_test.go

More (not all) special chars now mapped
Refer https://github.com/openconfig/goyang/issues/112

Extend enum assigned name mapping (special chars)

---

demo/gnmi_telemetry/gnmi_test.go
scripts/coverage.sh
testutil/diff.go
testutil/diff_test.go
util/gnmi_test.go
util/reflect_test.go
ygen/codegen_test.go
ygen/gogen_test.go
ygen/protogen_test.go
ygen/schemaparse_test.go
ygot/diff_test.go
ygot/schema_test.go
ygot/struct_validation_map_test.go
ypathgen/pathgen_test.go
ytypes/leaf.go
ytypes/schema_tests/get_test.go
ytypes/schema_tests/set_test.go

- Slight style improvement in ytypes/leaf.go
- Add test for GenerateUnifiedDiff
- Change remaining instances of Diff(got, want) to Diff(want, got) for consistency.
- Remove some non-library code from the coverage count.
Background: see https://github.com/openconfig/ygot/pull/319#issuecomment-543409852

Style improvements

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go

Merged two overlapping functions into one.
Before:
`makeKeyMapStrs` returns (name, varName) for each list parameter key.
`makeParamListStrs` returns (varName, typeName) for each list parameter key.
After:
`makeKeyParams` returns (name, varName, typeName) for each list parameter key.

Simplify Key-Processing Functions in ypathgen

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

The DeepCopy performed in MergeStructs can be expensive. This provides a
more efficient merging function which allows smaller inputs to be more
efficiently copied into a larger destination struct.
Tests are mostly shared between the two merge functions as they share
the same copying code.

Add a merge function that mutates inputs

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

```
* (M) ygot/struct_validation_map(_test)?.go
- Resolve bug with merging enums where an unset value would overwrite
a set value.
- Resolve bug with merging enums where an error would not be thrown
when the values were explicitly set to different values.
- Resolve bug with merging unions where two unequal values would not
result in an error being thrown.
- Resolve bug with merging unions where an unset value would overwrite
a set value.
```

Fix defects in merging structs for enums and unions.

---

ygot/diff_test.go
ytypes/leaf.go
ytypes/leaf_list.go
ytypes/leaf_list_test.go
ytypes/leaf_test.go
ytypes/unmarshal.go

Also add a corner case test for ygot.Diff.
NOTE: A nil TypeValue currently doesn't fail, and it looks to be implemented that way. I can change it if this doesn't make sense.
e.g.
```
func unmarshalLeafList(schema *yang.Entry, parent interface{}, value interface{}, enc Encoding) error {
if util.IsValueNil(value) {
return nil
}
```

Error out on nil input values when doing gNMI Encoding unmarshalling

---

ygen/enumgen.go

- Split out `identityBaseKey`, `enumeratedTypedefKey`, and `enumeratedLeafKey` functions from their respective name generation functions.
- Reorganize order of functions within enumgen.go to make the next PR less crazy.

Split each enum class's unique key calculation into separate functions

---

go.mod
go.sum
ygot/render.go
ygot/render_test.go

Currently, the jsonTree (`map[string]interface{}`) construction is done incorrectly due to a `json.Unmarshal` call on the marshalled data from the custom `Marshaler`, which doesn't make sense if the two calls are not compatible.
I believe the reason Marshal+Unmarshal is done is to copy the data, so instead I've used an MIT licensed library to do a deepcopy so that the final jsonTree contains the `Annotation` struct directly, meaning that a subsequent `json.Marshal` will call the customized `MarshalJSON` function.
Although I don't see how using the `Annotation` struct directly instead of a `map[string]interface{}` would create any new problems, it still doesn't solve the problem of how to unmarshal from bytes to the jsonTree correctly, but I saw this so I'm assuming this is irrelevant for …

Create Annotation JSON Tree using deepcopy instead of Marshal+Unmarshal

---

ygot/render.go
ygot/render_test.go

```
* (M) ygot/{render,render_test}.go
- Some users wish to be able to render a specific field to
RFC7951 JSON directly, such that a particular subtree can be
rendered.
Today, this is not possible since we require arguments to the
rendering functions to be specified as GoStructs. This PR adds
a new rendering method that specifically takes an interface{}
and returns a string such that these users can call this method
generically for any valid input type of a ygen generated Go file.
We lose some type-safety in this mechanism, but this is similar to
the interface provided by json.Marshal.
This method is implemented only for RFC7951 JSON, as we aim to
move away from the 'internal' format (which today is only
supported for marshalling and not unmarshalling).
```

Add a new mechanism for rendering rfc7951 JSON.

---

exampleocpath/ocpath_augment.go
ygot/path_types.go
ygot/path_types_test.go
ypathgen/generator/generator_test.go
ypathgen/path_tests/path_test.go
ypathgen/pathgen.go
ypathgen/pathgen_test.go
ypathgen/testdata/structs/choice-case-example.path-txt
ypathgen/testdata/structs/enum-module.path-txt
ypathgen/testdata/structs/openconfig-augmented.path-txt
ypathgen/testdata/structs/openconfig-camelcase.path-txt
ypathgen/testdata/structs/openconfig-enumcamelcase.path-txt
ypathgen/testdata/structs/openconfig-simple-0.path-txt
ypathgen/testdata/structs/openconfig-simple-1.path-txt
ypathgen/testdata/structs/openconfig-simple-30.path-txt
ypathgen/testdata/structs/openconfig-simple-31.path-txt
ypathgen/testdata/structs/openconfig-simple-32.path-txt
ypathgen/testdata/structs/openconfig-simple-40.path-txt
ypathgen/testdata/structs/openconfig-simple-41.path-txt
ypathgen/testdata/structs/openconfig-simple-42.path-txt
ypathgen/testdata/structs/openconfig-simple-43.path-txt
ypathgen/testdata/structs/openconfig-simple-intendedconfig.path-txt
ypathgen/testdata/structs/openconfig-simple.path-txt
ypathgen/testdata/structs/openconfig-unione.path-txt
ypathgen/testdata/structs/openconfig-withlist-builder.path-txt
ypathgen/testdata/structs/openconfig-withlist.path-txt

Merge its functionality into `ResolvePath` in `ygot/ygot`. This reduces complexity in the generated code.
The reason why this function was needed in the generated code instead of being able to reside in `ygot/ygot` was it needed to access special fields from the generated root `PathStruct`. Using the pattern analogous to `ygot.NodePath`, a base struct `DeviceRootBase` is defined along with an interface that the generated root object embeds. This allows `ygot` to access those root struct fields.

Remove Resolve function from generated code

---

.github/workflows/go.yml

This PR resolves an issue with coveralls reporting coverage based on some recent changes. I moved to just a pre-canned action so that we can rely on their integration testing.

Update call in goveralls checking.

---

ygot/struct_validation_map.go

When the `ValidatedGoStruct` is of considerable size, `EmitJSON()` method takes significant memory resource even though skipValidation is `true`. 
This change can reduce the memory utilization while using EmitJSON with `skipValidation=true`

check skipValidation before calling Validate

---

ygen/.vscode/settings.json
ygen/genir.go
ygen/genir_test.go
ygen/ir.go

This PR adds an initial set of types for the generation of the
ygen IR per the previously submitted design document. The code
is not currently exercised, but starts as a safe manner to make
these changes to ygen.
```
* (A) ygen/genir(_test).go
- Add code file for public-facing API for ygen IR
generation.
* (A) ygen/ir.go
- Add code file defining the ygen IR.
```

Add initial framework for IR generation.

---

ytypes/util_test.go
ytypes/util_types.go

This is a bug fix to `stringToKeyType`.

Allow keys fields that are themselves leafrefs to be unmarshalled.

---

testutil/types.go
ytypes/int_type.go
ytypes/leaf.go
ytypes/leaf_test.go
ytypes/leafref_test.go
ytypes/list_test.go
ytypes/string_type.go
ytypes/util_test.go

Added testutil/types.go for unit-testing new Go union concrete types. These are the same as what would be generated by ygen in a new flag for generating these simpler unions.
Validate functionality is modified to be able to validate either a code on the old union API or the new union API. I use the adjective "simple" to describe the new unions in tests, and added `(wrapper union)` to the descriptors of the tests for the old union types. This helps remove this functionality when we elevate the flag to be the normal behaviour.
This is the first of a series of PRs that add support and unit testing to the ytypes/ygot packages. The new code generation will be added last, after the support code (ytypes/ygot) is ready.

Add support for new Go unions for ytypes' Validate functions

---

ygot/diff.go
ygot/diff_test.go

The enum value needs to be extracted from the union interface first. This is due to missing test coverage, which is now added.

Fix bug where simple union enums causes panic within ygot.Diff.

---

ygen/genstate.go
ygen/genstate_test.go
ypathgen/pathgen.go
ypathgen/pathgen_test.go
ypathgen/testdata/structs/enum-module.path-txt
ypathgen/testdata/structs/openconfig-camelcase.path-txt
ypathgen/testdata/structs/openconfig-withlist-builder.path-txt
ypathgen/testdata/structs/openconfig-withlist-separate-package.path-txt
ypathgen/testdata/structs/openconfig-withlist.path-txt

Whenever a list path constructor has a parameter, it has a docstring on the valid types for the parameter.
This is mostly useful for knowing which types are valid for unions when constructing list paths using `ypathgen`.
e.g.
```
// Neighbor: string
// SidId: [UnionUint32, E_MplsTypes_MplsLabel_Enum, UnionString, E_AdjacencySid_SidId]
```
Since the old unions are no longer recommended, only new union names are displayed.

Add docstring on valid types for list keys for list constructors

---

.github/workflows/go.yml
ygen/codegen.go

Resolves #470 
The unsupported node here is the **child node**, so displaying the parent node is confusing.

Improve Error Message for findMappableEntities

---

ygot/diff.go
ygot/diff_test.go
ygot/render_test.go

Add a check for the default value to the bail condition in `findSetLeaves`. Resolves #473 
Currently, the default value of `false` for `YANGEmpty` is counted as set by `findSetLeaves`. This is clearly not what `findSetLeaves` intended, as the only form of a set `YANGEmpty` is `true`.

Ignore default data values in findSetLeaves

---

generator/generator.go
ygen/codegen.go
ygen/schemaparse.go
ygen/schemaparse_test.go

Currently YANG descriptions are dropped to reduce the size of generated schema.
Sometimes the descriptions are needed in the generated schema.
This patch adds the ability to specify an `-include_descriptions` flag on the `generate` command

ygen: Option to include descriptions in generated schema

---

ytypes/schema_tests/posix_regex_benchmark_test.go
ytypes/string_type.go

If there are a lot of routing prefixes to be validated, regexp compilation can become a performance bottleneck.
Aside: This could be because Go's regexp implementation might be relatively slow compared to other languages: https://github.com/golang/go/issues/11646

Cache regexp compilations during string validation.

---

proto_generator/protogenerator.go
ygen/codegen.go
ygen/codegen_test.go
ygen/protogen.go
ygen/testdata/proto/enum-union.compress.enums.formatted-txt
ygen/testdata/proto/enum-union.compress.formatted-txt
ygen/testdata/proto/excluded-config-false.uncompressed.formatted-txt
ygen/testdata/proto/proto-test-c.proto-test-c.elists.elist.formatted-txt
ygen/testdata/proto/proto-test-c.proto-test-c.elists.formatted-txt
ygen/testdata/proto/proto-test-c.proto-test-c.entity.formatted-txt
ygen/testdata/proto/proto-test-c.proto-test-c.formatted-txt

`protoc-gen-go` now requires an explicit `go_package` annotation to specify the name of the package that is being generated. This change adds this to protobuf packages that are generated by ygot.
A new `go_package_base` option is added to the `proto_generator` binary and the name of the package put into generated packages.

Add go_package Annotation to generated protobufs.

---

ygot/render.go
ygot/render_test.go

Encode empty list as empty list for RFC7951. Correct formating

fixes #526, encode empty list as empty list when using RFC7951 encoding

---

ygot/render.go
ygot/render_test.go
ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

This allows a user who is looking to multiplex config and telemetry operations on the same set of GoStructs to treat the GoStructs as either a config struct or a telemetry struct by simplying tweaking this marshal flag.

Add a new JSON marshal option that prefers the shadow path name.

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go

This field is the same as `GoTypeName`, but omits the `schemaStructPkgAccessor`. This may be useful for downstream users.

Add LocalGoTypeName to NodeDataMap for ypathgen

---

.github/workflows/go.yml

Increase coverage to include go1.16.
Going forward, it'd be great to figure out whether there's a go-latest or similar
such that we can include that. Although we say that we support $latest-3 versions,
I think it'd be nice to just keep testing until such time as we find a reason to
need to deprecate the oldest version.
Thoughts?﻿

Add Go 1.16 to CI testing.

---

protomap/proto.go
protomap/proto_test.go

``` 
* (M) proto/proto.go
* (M) proto/proto_test.go
- Add support for unmarshalling a map of gNMI.Path->value into
a ygot-generated protobuf. This is done by ranging over the
protobuf message and using the annotated paths.
- Initial implementation just supporting string type.
```
This implementation just handles a simple string type, but TypedValue is to be added later such that we can do this directly from gNMI Notifications.
This change starts to implement the 2nd half of the pipeline of:
(new, this PR) `GoStruct->gNMI Notifications->Protobuf`
- GoStruct -> gNMI Notifications is `ygot.TogNMINotifications`
- gNMI Notifications -> Protobuf is `protomap.PathsFromProto`
GoStruct<-gNMI Notifications<-Protobuf
- Protobuf <- gNMI Notifications is this code.
- GoStruct <- gNMI Notifications is …

Add initial implementation of unmarshalling gNMI Notifications->pb.

---

ygot/render.go
ygot/render_test.go

```
* (M) ygot/render.go
* (M) ygot/render_test.go
- This change allows the contents of the `module` tag to be rewritten
when outputting RFC7951-compatible JSON. Particularly, this is
useful when a node that was removed from the schema is re-added
using an augmentation, and the user wants to specify that ygot
should pretend that the node is still in the original module.
```

Add support for rewriting the appended module name.

---

go.mod
go.sum
ygen/gogen.go
ygen/gogen_test.go
ygen/testdata/structs/openconfig-list-enum-key.formatted-txt
ygot/render_test.go
ytypes/node_test.go

Currently for compressed schema GoStructs, we only put the key path in the `path` annotation of the struct tags, e.g. `path:"index|state/index" shadow-path:"config/index"`. However, when a compressed GoStruct is to be used either as a config object or a state object, we need to be able to marshal the key path as well, e.g. in order to create a valid JSON.
This PR proposes to make the path tags `path:"index|state/index" shadow-path:"index|config/index"`.
This change only affects behaviour when `shadow-path` is ever used for marshalling or unmarshalling. e.g. when `PreferShadowPath` is turned on when marshalling JSON, or when `ReverseShadowPath` is turned on for Set/GetNode.
I updated all three `exampleoc`s, but only `opstateoc`'s generated code was affected by this PR alone.

Add key to shadow-path annotation.

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go

This helps the consuming code process the fake root as well.

Add Fakeroot to NodeDataMap return value for ypathgen's GeneratePathCode.

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go

This enables downstream code using the library to determine which leaves have default values assigned for them.

Add HasDefault field to nodeDataMap returned by ypathgen

---

ygot/diff.go
ygot/diff_test.go

Useful when you just want to check that block X is a subset of block Y.

Add DiffOption to only consider original paths.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go
ygot/testdata/emitjson_1_html_safe.json-txt

Alternatively I can remove this option altogether, let me know, I'm fine either way.

Hide EscapeHTML behind an option instead of default behaviour.

---

ygot/path_types.go
ygot/path_types_test.go

Per the spec it should be `path := []*PathElem{}` rather than `nil` as
it currently is.
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-path-conventions.md#constructing-paths

[ypathgen] ResolvePath should return a non-nil PathElem message.

---

ypathgen/pathgen.go
ypathgen/pathgen_test.go

Add GoPackage field to path NodeData so that downstream generators can use the package name.

add GoPackage to NodeData

---

.gitignore
util/reflect.go
ygen/directory.go
ygot/diff.go
ygot/struct_validation_map.go
ytypes/leafref.go
ytypes/util_json.go

From [cmp](https://pkg.go.dev/github.com/google/go-cmp/cmp):
```
This package is intended to be a more powerful and safer alternative to
reflect.DeepEqual for comparing whether two values are semantically
equal. It is intended to only be used in tests, as performance is not a
goal and it may panic if it cannot compare the values. Its propensity
towards panicking means that its unsuitable for production environments
where a spurious panic may be fatal.
```

Use reflect.DeepEqual instead of cmp.Equal.

---

ygot/render.go
ygot/schema_tests/schema_test.go

This seems to significantly improve the performance for a particular use case we have.
I didn't see any real concerns for removing the deep copy from the user's perspective. Already we're doing a shallow copy for the `parentPath` when going down a container, so I don't see why we can't do the same for each list value:
https://github.com/openconfig/ygot/blob/032d1f4934c23eef44b0460b010e1be9a93a8015/ygot/struct_validation_map.go#L63-L66
```
BenchmarkNotificationOutput-12                     10000            107130 ns/op <-
BenchmarkNotificationOutputElement-12              14344             83329 ns/op
```
```
BenchmarkNotificationOutput-12                     12613             95651 ns/op <-
BenchmarkNotificationOutputElement-12              14298             84451 ns/op
``` …

Do not Clone `PathElem`s when creating a map value's path.

---

.github/workflows/go.yml

Currently, the scheduled build runs are failing due to unresolved references in the HEAD of staticcheck.

Specify latest release of staticcheck rather than HEAD.

---

ytypes/container.go

```
* (M) ytypes/container.go
- Since schemas that are generated with annotations will always
generate the log that says that unmarshal into them is unsupported
the log message produced is extremely low value to a user. To this
end - just remove it.
```
@wenovus -- I concluded that it was just higher-value to remove this entirely. Given that the user knows that they generated the code with annotations, then I'm not sure they ever will have value from this log.
An alternative would be to check that the annotation field was populated, and then produce this log, but I think this seems like we should just implement unmarshalling annotations. I can look at this as a future task.

Remove log that is always generated for annotation fields.

---

ygen/directory.go
ygen/genir_test.go
ygen/ir.go

This value corresponds to
https://datatracker.ietf.org/doc/html/rfc7950#section-7.21.1
This is needed in order to finish refactoring ygnmi to use IR, which needs this value to know whether to allow a user to multiplex a path using a `dut.Telemetry().Interfaces("foo").Config()` and `dut.Telemetry().Interfaces("foo").State()`.
The reason I chose `ConfigFalse` instead of just `Config` is because "config true" is the default value and is much more common in the OpenConfig models.

Add `ConfigFalse` field to IR's `ParsedDirectories`.

---

testdata/modules/openconfig-complex.yang
ygen/enumgen.go
ygen/genir_test.go
ygen/testdata/proto/enum-union.compress.enums.formatted-txt

Currently for unions it uses the outer-most union for the name and the type classification, but it should rather use the namesake union instead.
The integration test changes are due to **unused enums** now removed from the generated file because these were inline enums that should never have been generated in the global enum file.

More accurate enum naming and classification according to namesake type.

---

generator/generator.go

This flag is for trimming the generate PathStruct package names, not any other package.

Change `-trim_package_prefix` to `-trim_path_package_prefix`

---

ygot/struct_validation_map_test.go

Using `pretty.Compare` has masked this issue. Since it's possible users might have already depending on the current behaviour I wanted to be conservative and just keep the current behaviour, which I think is reasonable -- given the current generated code essentially we're saying we'd initialize containers but not lists.

Remove expectation that nil maps and slices (YANG lists) are initialized by `BuildEmptyTree`

---

ygot/render_test.go

By Hyrum's Law (which is already observed for this particular case (https://github.com/openconfig/ygot/pull/685)), I think we should codify this so that this doesn't change over time.

Codify that nil map marshals to null in JSON

---

.github/workflows/go.yml

Exactly the same results:
* before: https://coveralls.io/builds/49771275
* after: https://coveralls.io/builds/49782021
This is to enable more flexible coverage reporting if there are cross-package unit tests.

Use bash instead of overalls

---

ytypes/gnmi.go
ytypes/gnmi_test.go
ytypes/node_test.go

Possible use cases:
* Maintaining a schema-aware view of the configuration at a gNMI server.
* Simulating the effects of a SetRequest to compare against results from a server.

Unmarshal SetRequest and Notification to a root GoStruct.

---

ytypes/gnmi.go
ytypes/gnmi_test.go

Otherwise it's confusing to the user who thinks it's a copy.

Remove ygot.GoStruct return from UnmarshalSetRequest since it's not a copy.

---

.github/workflows/go.yml

```
* (M) .github/workflows/go.yml
- Add authentication token to avoid failures due to API rate limit.
```
This fixes the failing cron'd CI runs.

Add authentication token for setup-protoc.

---

protogen/protogen.go
protogen/protogen_test.go
protogen/testdata/proto/nested-messages.compressed.nested_messages.formatted-txt
protogen/testdata/proto/nested-messages.nested_messages.formatted-txt

```
* (M) protogen/protogen(_test)?.go
- Add support for adding schema path annotations for unions that
are within leaf-lists. This is represented as a repeated
message rather than a single oneof.
* (M) protogen/testdata/*
- Update testing data.
```

Ensure that path annotations are created for leaf-list of unions.

---

.github/workflows/cifuzz.yml
.github/workflows/go.yml

Fixed as recommended in https://github.com/google/oss-fuzz/issues/9367#issuecomment-1400559396
```
2023-02-06 18:37:56,986 - root - INFO - Fuzzer fuzz_oc_unmarshall finished running without reportable crashes.
```

Add bad-build-check: false to CIFuzz & add 1.19 and 1.20 to Go CI

---

gnmidiff/json.go
gnmidiff/json_test.go

This is useful for comparing between two SetRequests whose contents are in JSON_IETF format.
It only intends to support OpenConfig-compliant JSON because it is otherwise impossible to infer the list keys from RFC7951 JSON.
@marcushines

Add utility `flattenOCJSON` in package `gnmidiff`

---

ytypes/leaf.go
ytypes/leaf_list_test.go
ytypes/leaf_test.go
ytypes/schema_tests/set_test.go

Show the type of the TypedValue, not just the value.
e.g. This was not a helpful message:
`failed to unmarshal &{[34 114 111 115 101 115 97 114 101 114 101 100 34]} into string`
This was much more helpful:
`failed to unmarshal (*gnmi.TypedValue_JsonVal, &{[34 114 111 115 101 115 97 114 101 114 101 100 34]}) into string`

Improve error message on unmarshalling a TypedValue

---

ytypes/node.go
ytypes/node_test.go

Should use JSON_IETF instead.
This is backwards-compatible because it was never handling JSON correctly, this change merely gives a better error message than before.

Return deprecation error message when unmarshalling using SetNode/JSON

---

.github/workflows/go.yml

The pre-1.17 versions are introducing problems for PRs such as https://github.com/openconfig/ygot/actions/runs/4207239816/jobs/7301781404 in https://github.com/openconfig/ygot/pull/784
Furthermore, I wanted to remove support for 1.17 since 1.18 is the first version of generics, and it allows us to introduce generics into ygot.
I believe this change is reasonable since 1.20 has just been released, so officially only 1.18 is no longer released, and ygot supports an extra version (1.18) as stated in the README.

Remove CI support for Go 1.13, 1.14, 1.15, 1.16, 1.17

---

protomap/proto.go

Remove use of the protoreflect `Syntax` API which is being migrated away from.

Remove usage of the proto Syntax call.

---

.github/workflows/go.yml
gnmidiff/json.go

The `gofmt` check required explicit opt in of directories - meaning that
`gofmt` issues could slip through the net.  This check makes it such that new
directories need to opt out.

Enable `gofmt` CI against new directories by default.

---

gnmidiff/intent.go
gnmidiff/intent_test.go
gnmidiff/setrequest_test.go
ygot/render_test.go

In gnmidiff for simplicity we want to have a uniform way of encoding values due to the chance that both JSON and TypedValue scalars can both be inputs at the same time. This means when diffing programmatically and visually (via CLI) the values can be compared apples-to-apples and it relieves the user of having to deal with type differences.
Previously `TogNMINotifications` was called which outputs scalars, but for uniformity `Marshal7951` is now used. There is actually no strict advantage to using TypedValue scalars due to the fact that YANG -> TypedValue conversion is lossy (namely all int/uint values get squished to int64/uint64), and so there is no way to accurately convert TypedValue scalar to  JSON since int64/int32 are treated differently.
Also double-val conversion is now done …

populateUpdate marshals JSON instead of TypedValue scalars

---

ygot/join.go
ygot/join_test.go
ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

Fail slow: gather error messages about conflicting fields prior to returning to user.
Also print the access path to the user so they know which fields contain the conflict.

Improve error messages in ygot.Merge.

---

gogen/internal/gotypes/ordered_map.go
gogen/internal/gotypes/ordered_map_test.go

Initially I made the choice to use a non-pointer so that the user would not need to initialize this field before using it.
The advantage is all methods can hang off of the type rather than needing methods to hang off the parent type in order to nil-check and initialize.
However, this creates problems that a pointer field solves:
1. Avoid needing value-receivers in order to make the field satisfy certain interfaces (e.g. ygot.GoStruct). Mixing receiver types is confusing for the reader.
2. Helps avoid awkward reflection code that need to access the pointer receiver methods since `CanAddr()=false` for non-pointer objects: https://go.dev/play/p/5vYVVUS-GfD
3. Users of ygot are used to declaring every struct as pointers, so using pointers makes things congruent with existing generated code. …

Make ordered maps a pointer in the parent GoStruct.

---

.github/workflows/go.yml
testutil/testutil.go
ygot/render.go
ygot/render_test.go
ygot/struct_validation_map_test.go

This is done by putting all values underneath an ordered map into a single, ordered list of Update values, which gets put into a separate Notification for return.

Marshal ordered maps into `atomic` gNMI notifications for `TogNMINotifications`

---

.github/workflows/go.yml
integration_tests/schemaops/ctestschema/ctestschema.go
integration_tests/schemaops/ctestschema/helpers.go
integration_tests/schemaops/ctestschema/update.sh
internal/yreflect/reflect_orderedmap.go
internal/yreflect/reflect_orderedmap_test.go
util/reflect.go
util/reflect_exported_test.go
util/types.go
ygot/render.go
ytypes/list.go
ytypes/node.go
ytypes/node_exported_test.go

* A new function was created for ordered maps. It resembles the existing one for unordered lists but refactored a bit and I intend to re-use the logic in the next PR.
* Generated test code was updated to output shadow paths for testing.
* Refactored util code a little and created internal yreflect util lib.

Support ytypes.GetNode for ordered maps.

---

util/gnmi.go
util/gnmi_test.go
ytypes/gnmi.go
ytypes/gnmi_exported_test.go
ytypes/gnmi_test.go
ytypes/list_exported_test.go
ytypes/node.go
ytypes/node_exported_test.go

Involves supporting `DeleteNode` at the container above the list for ordered maps.

Support unmarshalling an atomic `Notification` for ordered lists.

---

ygot/render.go
ygot/render_test.go

Also converted some of the ConstructJSON tests to use the correct types which didn't affect the test result, which shows that pretty.Compare doesn't compare them correctly.

`interface{}` -> `any` for render{_test}.go

---

integration_tests/schemaops/schemaops_compressed_test.go
integration_tests/schemaops/schemaops_test.go
internal/yreflect/reflect_orderedmap.go
util/reflect.go
util/reflect_exported_test.go
util/reflect_test.go
ygot/struct_validation_map.go
ygot/struct_validation_map_exported_test.go

For merge if there is any overlap it simply errors out -- I don't think there is a clear way of merging them if there is a partial overlap.
For overlaps where the second ordered list is a subset of the first, then I can see it as a valid merge -- however I'm opting for simplicity for now since this seems like a more advanced use case.

Support `ForEachDataField`, `DeepCopy`, `Merge` for ordered maps.

---

CONTRIBUTING.md

It looks like this section is outdated.
Thanks @lgomez9 for spotting.

Update CONTRIBUTING to remove section on internal syncs

---

util/reflect_exported_test.go
ygot/render.go
ygot/render_exported_test.go
ygot/render_test.go

Unfortunately Hyrum's law applies to ygot. I am reverting the normalizing behaviour for internal JSON generation.

Preserve some backward-compatibilities with certain render functions.

---

util/reflect_exported_test.go

Just addressing a comment I missed to push.

Make variable a function

---

generator/generator.go
gogen/codegen.go
gogen/codegen_test.go
gogen/gogen.go
gogen/internal/gotypes/ordered_map.go
gogen/testdata/structs/openconfig-withlist-opstate.formatted-txt
gogen/testdata/structs/openconfig-withlist-unordered.formatted-txt
gogen/unordered_list.go
testdata/modules/openconfig-withlist.yang
util/reflect.go
ygot/diff_exported_test.go
ygot/struct_validation_map_exported_test.go
ypathgen/pathgen_test.go
ypathgen/testdata/modules/oc-list/list.txt
ypathgen/testdata/structs/openconfig-withlist-separate-package.path-txt
ypathgen/testdata/structs/openconfig-withlist.builder.path-txt
ypathgen/testdata/structs/openconfig-withlist.nowildcard.path-txt
ypathgen/testdata/structs/openconfig-withlist.path-txt
ypathgen/testdata/structs/openconfig-withlist.simplifyallwc.path-txt

Flag is on by default to send a signal to downstream users to convert. The flag is used for transitioning existing code.
Tested generator manually. presubmit also has a test for it via integration_tests/schemaops and `go generate ./...`
* Added integration test
* Fixed a few typos

Add generation flag for ordered maps

---

util/reflect.go
util/reflect_test.go
util/walk.go

* ast.Walk: https://go.dev/src/go/ast/walk.go
* Rewrite ForEachField using the new `util.Walk` iterator, including supporting the PathQueryNodeMemo.
* Rewrite ForEachDataField and ForEachDataField2 using the new `util.Walk` iterator.
Resolves #889

Add an ast.Walk style iterator of GoStructs.

---

internal/yreflect/reflect_orderedmap.go
internal/yreflect/reflect_orderedmap_test.go
ygot/struct_validation_map.go
ygot/struct_validation_map_exported_test.go

when merging A <- B, and B is subset of A and the ordering of elements don't contradict, allow merging to occur.

Support subset merge for ordered maps

---

ygot/struct_validation_map.go
ygot/struct_validation_map_exported_test.go

OrderedMaps are map types, which are not supposed to be initialized by BuildEmptyTree.

Fix BuildEmptyTree for ordered maps

---

ygot/diff.go
ygot/diff_exported_test.go
ygot/render.go
ygot/render_test.go

Previously it was ignoring this flag for ordered maps when calling `ygot.DiffWithAtomic`

Support shadow-paths for ordered map Diff

---

exampleoc/opstateoc/update.sh
exampleoc/update.sh
gogen/codegen.go
gogen/testdata/schema/openconfig-options-explicit.formatted-txt
ytypes/schema_tests/set_test.go
ytypes/schema_tests/validate_test.go

* Fixed unmarshalling union leafs for shadow paths.
* Use correct path for keying `ΛEnumTypes`.
* Re-generate exampleoc for schema test.

Generate `ΛEnumTypes` for shadow paths

---

ytypes/validate.go

Even with debugLibrary not enabled ValueStr is calculated in this call, which causes significant bottlenecks in validation.
All other calls to DbgPrint already use ValueStrDebug to avoid formatting string output that won't ever be used.
In my test use case this changed performance from approximately 80s to 40ms.

Remove bottleneck in validation

---

ygot/diff.go
ygot/diff_test.go

Sample output:
```
deleted: /floatval
new/updated /int-val: int_val:10
```
```
no diff
```

ygot.FormatDiff

---

protomap/integration_tests/integration_test.go

```
* (M) protomap/integration_tests/integration_test.go
- Rename `gribi_aft` to `aftpb` to reflect standard protobuf library
naming.
```

Use standard protobuf library naming for gribi_aft.

---

testdata/modules/openconfig-simple-with-unsupported.yang
ygen/directory.go

Currently it fails because containers are being detected via the `default` case, so they're being classified as containers.

Support skipping any-xml using -ignore_unsupported.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

```
* (M) ygot/struct_validation_map(_test)?.go
- if a map was received that had a nil value in it, this caused
a panic to occur since `(reflect.Value).Elem()` does not handle
these cases cleanly. Add a check whether the value is nil before
calling Elem.
```

Avoid panic when calling Elem on a nil map member.

---

testutil/types.go
ygot/render.go
ygot/render_test.go

When `jsonValue` is called using the output of `reflect.ValueOf()` instead of `reflect.StructField`, any interface type is lost through re-packing to the empty interface (any). This means the `reflect.Kind` of a union field is no longer the union type, but instead its underlying concrete type. The current code doesn't handle this case, leading to runtime errors.
This handling code is now added, with a couple more fixes related to `empty` types.
-----
Tested manually that the following ygnmi call is no longer affected by the original error:
```go
sp := gnmi.OC().NetworkInstance("DEFAULT").Protocol(oc.PolicyTypes_INSTALL_PROTOCOL_TYPE_STATIC, "STATIC")
ygnmi.Replace(context.Background(), c, sp.Static("1.1.1.1/32").SetTag().Config(), …
```

Fix `Marshal7951` for direct union leaf calls.

---

.github/workflows/go.yml

```
* (M) .github/workflows/go.yml
- Remove testing support for go 1.18 -- these tests are failing
based on dependencies. Our contract here is to support -3
versions, so this is in-line with expecations of our consumers.
```
Fixes the failing CI @ HEAD.

Remove support for go 1.18.

---

util/reflect.go
ytypes/leaf.go
ytypes/node.go
ytypes/node_test.go
ytypes/schema_tests/set_test.go
ytypes/util_schema.go

```
* (M) util/reflect.go
- Fix missing parameter to string output.
* (M) ytypes/{leaf,node,node_test,schema_test,util_schema}.go
- Two bugs fixed.
1. In the case that one calls `SetNode` with something that was
not a gNMI `TypedValue` and was not JSON, then we could panic
when attempting to type cast it.
2. If a schema was generated that uses path compression, and
`SetNode` was called for a node that was compressed out, but
`PreferShadowPaths` was not set AND this node was a leaf-list
then rather than performing a no-op (the expected behaviour,
since we asked to set a node that was not the 'preferred' thing
to set), then we would bail with an error since the schema was
not a leaf schema. Small fix, lots of testing to find the root
cause here.
* (M) ytypes/schema_test/set_test.go
- Bug …
```

🐜: squash bug related to leaf-lists and shadow schemas.
