experimental/ygotutils/common.go
experimental/ygotutils/getnode.go
experimental/ygotutils/getnode_test.go

New functions:
- NewNode creates new node (GoStruct or leaf type) based on a root struct type and GNMI path
- GetNode returns a pointer to a node (GoStruct or leaf type) in an existing data tree based on a YANG schema and GNMI path

Add GetNode and NewNode utility functions.

---

.travis.yml
scripts/coverage.sh

```
* (M) .travis.yml
- Add trigger for coverage.
* (A) scripts/coverage.sh
- Script to run coverage for all packages.
```

Add coverage via coveralls.io

---

util/reflect_test.go

Move to pointer util functions inside the test package that uses them to remove ygot dep.

Remove dep on ygot.

---

ygen/codegen_test.go
ygen/genstate.go
ygen/goelements_test.go
ygen/gogen.go
ygen/gogen_test.go
ygen/protoelements_test.go
ygen/protogen_test.go
ygen/testdata/proto/proto-test-d.uncompressed.proto-test-d.test.formatted-txt
ygen/testdata/proto/proto-test-d.yang

This CL adds more test coverage for error cases in ygen.

Expand Test Coverage in ygen

---

docs/yang-to-protobuf-transformations-spec.md

Add public-facing document explaining YANG to Protobuf translation.

Add YANG to Protobuf transformation specification.

---

generator/generator.go
generator/generator_test.go
ygen/codegen.go
ygen/goelements.go
ygen/gogen.go
ygen/testdata/schema/openconfig-options-compress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-compress.formatted-txt
ygen/testdata/schema/openconfig-options-explicit.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress-fakeroot.formatted-txt
ygen/testdata/schema/openconfig-options-nocompress.formatted-txt

Add a generated map of schema path to the `reflect.Type`, see #51.

Add enum type map.

---

ygot/pathstrings.go

This is same as PathToString, but returns separated path elements in
a slice.

Add ygot.PathToStrings

---

ygen/genstate.go
ygen/schematree_test.go

Update references of ctree function Get to GetLeafValue.

Update ctree reference

---

ytypes/any_type_test.go
ytypes/binary_type_test.go
ytypes/bitset_type_test.go
ytypes/bool_type_test.go
ytypes/choice_test.go
ytypes/common_test.go
ytypes/container.go
ytypes/container_test.go
ytypes/decimal_type_test.go
ytypes/empty_type_test.go
ytypes/int_type_test.go
ytypes/leaf.go
ytypes/leaf_list_test.go
ytypes/leaf_test.go
ytypes/list_test.go
ytypes/string_type_test.go
ytypes/unmarshal_test.go
ytypes/validate_test.go

- Plug a few holes in coverage. 
- Change naming to be consistent. 
- Change test pattern to utilize subtests. 
Almost entirely mechanical changes.

Improve coverage, clean up tests.

---

ytypes/leafref.go
ytypes/leafref_test.go

This commit adds logic to ensure that a leaf-list data node that has a leafref to another leaf-list is a subset of the node it's pointing to.

Add validation for leafref from leaf-list to another leaf-list.

---

ygot/struct_validation_map.go
ygot/struct_validation_map_test.go

Fixes #175.
This PR adds the ability to merge two slice fields within a struct when the destination field is set. Previously, this would throw an error. The slices are checked for uniqueness so as not to violate RFC6020 constraints.

Add merge of slices fields to ygot.

---

demo/bgp/main_test.go
demo/device/devicedemo_test.go
demo/optical/opticaldemo_test.go
demo/uncompressed/uncompressed_test.go
testutil/diff.go
testutil/testutil.go
testutil/testutil_test.go
ygen/codegen_test.go
ygen/gogen_test.go
ygen/protogen_test.go
ygen/schemaparse_test.go
ygot/diff.go
ygot/diff_test.go
ygot/pathstrings_test.go
ygot/render_test.go
ygot/schema_test.go
ygot/schema_tests/schema_test.go
ygot/struct_validation_map_test.go
ytypes/schema_tests/validate_test.go

```
* (M) testutil/*
- This series of commits introduces an UpdateSetEqual and
NotificationSetEqual function which allows a set of updates or
Notifications to be compared to one another.
```

[2/4] Add implementation of Update + Notification set equality

---

demo/uncompressed/uncompressed_test.go
demo/uncompressed/yang/example.yang
util/reflect.go
util/reflect_test.go
ytypes/leaf.go
ytypes/leaf_test.go
ytypes/util_test.go
ytypes/util_types.go

```
* (M) ytypes/*
- Add support for unmarshalling the YANG empty type - which is
serialised as [null].
```

Add support for unmarshalling YANG empty type.

---

util/reflect.go
util/reflect_test.go

This change is part of a bigger change towards unmarshalling a gNMI notification into a GoStruct. This helper will be used initialize fields of GoStruct corresponding to the path element while walking on the GoStruct to validate given gNMI path.

Add helper to initialize pointer and composite struct fields

---

ytypes/node.go
ytypes/node_test.go

```
* (M) ytypes/node.go
- Add an implementation of GetNode that does not modify the tree
when querying.
- Fix retrieveNode implementation to handle queries that have
partial key specification and return them.
* (M) ytypes/node_test.go
- Add specific error handling test cases.
```

Add implementation of GetNode, error handling test cases.

---

ygot/diff.go
ytypes/node_test.go
ytypes/schema_tests/diff_benchmark_test.go
ytypes/schema_tests/testdata/interfaceBenchmarkA.json
ytypes/schema_tests/testdata/interfaceBenchmarkB.json

The performance of the ygot.diff.go is poor.
Therefore I tried to optimise it a bit.

Optimisation of diff performace

---

.travis.yml

version 1.13 has just released: https://blog.golang.org/go1.13

add support for Go versions 1.12 and 1.13

---

docs/design.md
genutil/common.go
ygen/gogen.go

Fix outdated design doc comment and a couple other comments.

Fix some comments

---

demo/protobuf_getting_started/demo.go
demo/protobuf_getting_started/demo_test.go
ygot/testdata/exschemapath/gen.go

``` 
* (M) ygot/testdata/exschemapath/gen.go
- Update to package comment to match Go style guidelines.
* (M) demo/protobuf_getting_started/{demo,demo_test}.go
- Rename protobuf imports to end in pb per style guidelines.
```

Minor updates to comply with Go style rules.

---

genutil/names.go
genutil/names_test.go

```
* (M) genutil/{names,names_test}.go
- Fix a couple of TODOs for missing unit test coverage.
```

Add coverage for genutil functions.

---

go.mod
go.sum

Use new goyang dependency that fixes decimal64 typedef range parse bug

---

ytypes/validate.go
ytypes/validate_test.go

Enable customValidation on root

---

genutil/common.go
ygen/codegen.go
ypathgen/pathgen.go

Fix misusages of `AppendErr` function.

Fix AppendErr statements

---

genutil/common.go
ygen/protogen.go
ygot/pathtranslate/pathtranslate.go
ygot/pathtranslate/pathtranslate_test.go
ygot/render.go
ytypes/list_test.go
ytypes/node.go

This change fixes a number of common typos that were present, and makes
a change to more inclusive language.

Correct a number of typos in the codebase.

---

ytypes/node.go
ytypes/node_test.go

reverseShadowPaths -> preferShadowPath

Change reverseShadowPath -> preferShadowPath for [Getxxx|Set]Node functions

---

ygen/gogen.go
ygen/gogen_test.go
ygen/testdata/structs/enum-module.formatted-txt
ygen/testdata/structs/enum-module.wrapper-unions.formatted-txt
ygen/testdata/structs/enum-union-with-enum-defaults.formatted-txt
ygen/testdata/structs/enum-union.consistent.formatted-txt
ygen/testdata/structs/enum-union.formatted-txt
ygen/testdata/structs/openconfig-list-enum-key.leaf-getters.formatted-txt
ygen/testdata/structs/openconfig-simple-excludestate.formatted-txt
ygen/testdata/structs/openconfig-simple-no-compress.formatted-txt
ygen/testdata/structs/openconfig-simple.formatted-txt

This was missed in https://github.com/openconfig/ygot/pull/237/files#diff-b75c80aad7fc147614bd565f03ab0194af2b76410e8862d976615f92355845df
Thanks to @dan-lepage for catching this.

Update leaf getter comment to say default value will be returned when unset.

---

util/reflect.go
util/reflect_test.go
util/yang.go

Also remove TODOs on a couple of trivial functions. Adding tests seem to add little value.

Add tests for util.ChildSchema

---

util/path.go
util/path_test.go

Sometimes we want not just the string path, but the entry path as well.

Add util helper SchemaEntryPathNoChoiceCase

---

util/yang.go

ReadOnly()'s implementation is a bit more robust, and has the same functionality.

Replace IsConfig()'s implementation with goyang's ReadOnly().

---

go.mod
go.sum

Remove the replace statement in the go.mod erroneously added in the last PR.

Fix goyang imports

---

.github/workflows/go.yml
util/reflect.go
ytypes/leaf_list.go
ytypes/leaf_list_test.go
ytypes/node_test.go

This is because gNMI doesn't allow for specifying deleting any specific leaf-list element.
I put `clearSliceField` in `ytypes` to avoid exposing this as a public function.

Fix leaf-list Unmarshal to replace instead of appending values.

---

util/path.go
util/yang.go
util/yang_test.go
ygen/directory.go

Follow-up of https://github.com/openconfig/ygot/pull/655#discussion_r859286770

Rename util.SchemaTreeRoot -> util.TopLevelModule

---

.github/workflows/cifuzz.yml
go.mod
go.sum

Disable running CIFuzz until this is not flaky.

Disable CIFuzz being run on PRs.

---

gogen/gogen.go
gogen/testdata/structs/openconfig-versioned-mod.formatted-txt

we celebrate small ~~PRs~~ wins
/cc @wenovus

Use tab indentation for modules listing

---

generator/generator.go

fix #768 
Hi @wenovus, does this match what you suggested in #768

Fix genenerator's flag descriptions

---

protogen/protogen.go
ygot/struct_validation_map.go

```
* (M) protogen/protogen.go
- check for correct errors being nil.
* (M) ygot/struct_validation_map.go
- remove dependency on cmp in non-testing code.
```

Address gobugs issues.

---

util/gnmi.go
util/gnmi_test.go

i also broke the circular dependency by renaming the package in this file to util_test

Add ComparePath func

---

gnmidiff/set_to_get_test.go

Not supported, so throws error.

Add test for DiffSetRequestToNotifications delete

---

gnmidiff/README.md
gnmidiff/diff.go
gnmidiff/setrequest.go
gnmidiff/setrequest_test.go

SetRequest diff description indicates that deletes may be replaces as well.

Improve output description for SetRequest diff.

---

util/gnmi.go
util/gnmi_test.go
util/reflect.go
util/yang_test.go
ytypes/common_test.go
ytypes/gnmi.go
ytypes/gnmi_exported_test.go
ytypes/gnmi_test.go
ytypes/leafref.go
ytypes/leafref_test.go
ytypes/list_exported_test.go
ytypes/node.go
ytypes/node_exported_test.go
ytypes/node_test.go

Added a new option to allow the transition to be made.

Deprecate `util.GetNodes` in favour of `ytypes.GetNode`

---

gogen/unordered_list.go
gogen/unordered_list_test.go

ygnmi will soon support querying for a map of objects. This functionality is required for that.

Export function for determining name of a keyed, unordered map.

---

gogen/genir_test.go
protogen/genir_test.go
ygen/directory.go
ygen/ir.go

This aligns things with YANGDetails

Add SchemaPath field to ParsedDirectory
